#### 镜像上传
# 仓库私服： aliyun
# 第一步：上传镜像到docker仓库
#docker tag jeecg-boot-mysql registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg/jeecg-boot-mysql:1.1
#docker push registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg/jeecg-boot-mysql:1.1
#docker tag nginxhtml:jeecgboot registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg/nginxhtml:1.2
#docker push registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg/nginxhtml:1.2

#docker login --username=llyfllyf@126.com registry.cn-hangzhou.aliyuncs.com    password 12345678abc
#docker tag jeecg-boot-system registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg-boot:1.0
#docker push registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg-boot:1.0

# 第二步：将此yml文件上传服务器，执行启动命令 docker-compose -f ./docker-compose-server.yml up
version: '2'
services:
#  jeecg-boot-mysql:
#    image: registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg/jeecg-boot-mysql:1.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    restart: always
#    container_name: jeecg-boot-mysql
#    command:
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
#      --max_allowed_packet=128M
#    ports:
#      - 3306:3306
#
#  jeecg-boot-redis:
#    image: redis:5.0
#    ports:
#      - 6379:6379
#    restart: always
#    container_name: jeecg-boot-redis

  jeecg-boot-system:
    image: registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg-boot:1.0
    restart: always
    container_name: jeecg-boot-system
    volumes:
      - /data/config:/jeecg-boot/config
    ports:
      - 8080:8080

#  jeecg-boot-nginx:
#    image: registry.cn-hangzhou.aliyuncs.com/007nas_top/jeecg/nginxhtml
#    restart: always
#    container_name: jeecg-boot-nginx
#    ports:
#      - 80:80
